### ISSUE TITLE
metadata-generation-failed

### ISSUE THREAD

**Issue by wayner6** [0n0gard/visual-chatgpt#1]
When i use `pip install -r requirement.txt` command, it occurs
My installed Python edition is **3.8**

![image](https://user-images.githubusercontent.com/88063517/224667743-8080d0b2-5a50-427d-beb0-fc961420df4d.png)

![image](https://user-images.githubusercontent.com/88063517/224667761-560e5324-12b8-4f4c-9256-44e5b9b26339.png)

Can you help me to solve it?

**Comment by Amazingldl** [comment]
换源试试，最好是官方源
https://pypi.python.org/simple

**Comment by yyyy-xxxx** [comment]
I get this wrong as you。if you see the first paragraph error，it tell you cpython not match。you can use “pip install cpython” to solve this problem。And then you can go with it。

**Comment by wayner6** [comment]
@0n0gard 降级pip解决了
